#!/usr/bin/env node
// jsinn post-processing: cleans up nim js output after macro rewriting

import { readFileSync, writeFileSync } from "fs";

// Dead runtime variables that nim js always emits but are never used
// when jsinn macros eliminate stdlib dependencies.
const DEAD_HEADER_VARS = new Set([
  "framePtr",
  "excHandler",
  "lastJSError",
]);

/**
 * Strip the dead Nim runtime header:
 * - /* Generated by the Nim Compiler vX.Y.Z *​/
 * - var framePtr = null;
 * - var excHandler = 0;
 * - var lastJSError = null;
 * - var objectID_NNNN = [0];
 */
export function stripHeader(source) {
  const lines = source.split("\n");
  const kept = [];
  let leadingBlank = true;

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip the Nim compiler comment
    if (trimmed.startsWith("/* Generated by the Nim Compiler")) continue;

    // Skip known dead runtime vars
    const varMatch = trimmed.match(/^var\s+(\w+)\s*=/);
    if (varMatch) {
      const name = varMatch[1];
      if (DEAD_HEADER_VARS.has(name) || name.startsWith("objectID_")) continue;
    }

    // Skip leading blank lines after stripping
    if (leadingBlank && trimmed === "") continue;
    leadingBlank = false;

    kept.push(line);
  }

  return kept.join("\n");
}

// CLI: node postprocess.mjs <input> [output]
const args = process.argv.slice(2);
if (args.length >= 1) {
  const input = readFileSync(args[0], "utf-8");
  const output = stripHeader(input);
  if (args[1]) {
    writeFileSync(args[1], output);
  } else {
    process.stdout.write(output);
  }
}
